import { PageHero } from '../components/PageHero'
import type { Crumb } from '../components/Breadcrumbs'
import { Eyebrow } from '../components/Eyebrow'
import { ArrowRight, Check, FileText, Leaf, Recycle, ShieldCheck, TriangleAlert, Waves } from 'lucide-react'
import { Link } from '../components/router'

const ASSET = '/uploads/'

type Navigate = (to: string) => void

function InstitutionalHero({ eyebrow, title, description, crumbs }: { eyebrow: string; title: string; description: string; crumbs?: Crumb[] }) { return <PageHero eyebrow={eyebrow} title={title} description={description} crumbs={crumbs} /> }

function ResourceCard({ icon, title, text, href, external = false }: { icon: React.ReactNode; title: string; text: string; href?: string; external?: boolean }) {
  const content = <><span className="resource-icon">{icon}</span><h3>{title}</h3><p>{text}</p>{href && <span className="text-link">{external ? 'Abrir recurso externo' : 'Conhecer conteúdo'} <ArrowRight size={15} /></span>}</>
  if (!href) return <article className="resource-card">{content}</article>
  return external ? <a className="resource-card" href={href} target="_blank" rel="noreferrer">{content}</a> : <Link to={href} className="resource-card">{content}</Link>
}

export function LegalDisposition({ navigate }: { navigate: Navigate }) {
  return <><InstitutionalHero eyebrow="Diretriz do projeto" title="Disposição Legal" description="Uma agenda de cooperação para transformar a destinação dos resíduos sólidos em Mato Grosso do Sul." crumbs={[{ label: 'Início', href: '/' }, { label: 'Disposição Legal' }]} /><section className="institutional-section section container"><div className="institutional-grid"><article className="prose"><Eyebrow>Por que este projeto existe</Eyebrow><h2>Conhecimento para cuidar do território</h2><p>O Projeto Resíduos Sólidos — Disposição Legal nasceu do diagnóstico dos principais aspectos relacionados à gestão, ao gerenciamento e à disposição final dos resíduos sólidos nos 79 municípios de Mato Grosso do Sul.</p><p>O trabalho reúne Ministério Público, universidade e instituições públicas para apoiar decisões, fortalecer os municípios e estimular soluções ambientalmente adequadas para resíduos e rejeitos.</p><p>A atuação combina informação técnica, cooperação e acompanhamento dos resultados. O objetivo é fazer com que cada município tenha referências para planejar, executar e melhorar seus serviços.</p><div className="quote-panel"><strong>Gestão responsável começa com informação confiável.</strong><span>Materiais, ferramentas e cooperação para transformar decisões em práticas.</span></div></article><aside className="institutional-aside"><div className="aside-stat"><strong>79</strong><span>municípios acompanhados pelo projeto</span></div><div className="aside-stat"><strong>2015</strong><span>início do diagnóstico estadual</span></div><div className="aside-stat"><strong>5%</strong><span>de municípios com disposição inadequada após a força-tarefa</span></div></aside></div></section><section className="resource-band"><div className="container"><Eyebrow>Próximos caminhos</Eyebrow><h2>Explore as soluções desenvolvidas</h2><div className="resource-grid"><ResourceCard icon={<Recycle />} title="Modelo de usinas de triagem" text="Referência para estruturar uma alternativa de triagem e valorização dos resíduos." href="/modelo-de-usinas-de-triagem-de-residuos/" /><ResourceCard icon={<ShieldCheck />} title="Sobre o projeto" text="Conheça a história, as instituições parceiras e a transformação observada no Estado." href="/#sobre-projeto" /><ResourceCard icon={<FileText />} title="Produções do convênio" text="Acesse estudos, planos municipais e materiais de apoio já produzidos." href="/producoes-do-convenio/" /></div><Link to="/producoes-do-convenio/" className="button button-dark institutional-cta">Ver todas as produções <ArrowRight size={16} /></Link></div></section></>
}

export function PlantModel({ navigate }: { navigate: Navigate }) {
  return <><InstitutionalHero eyebrow="Infraestrutura e planejamento" title="Modelo de Usinas de Triagem de Resíduos" description="Uma referência arquitetônica para apoiar municípios na implantação de estruturas de triagem." crumbs={[{ label: 'Início', href: '/' }, { label: 'Disposição Legal', href: '/disposicao-legal/' }, { label: 'Modelo de Usinas de Triagem' }]} /><section className="institutional-section section container"><div className="institutional-grid"><article className="prose"><Eyebrow>Projeto arquitetônico</Eyebrow><h2>Da disposição final à valorização dos materiais</h2><p>O modelo de usina de triagem organiza o recebimento, a separação e o encaminhamento dos resíduos recicláveis. Ele serve como referência técnica para que cada município avalie sua estrutura e adapte a solução à sua realidade.</p><p>A implantação de uma unidade de triagem deve ser acompanhada de planejamento operacional, segurança para os trabalhadores, controle de rejeitos e integração com a coleta seletiva e as cooperativas.</p><div className="check-list"><div><Check size={18} /><span>Fluxos de recebimento e triagem mais claros.</span></div><div><Check size={18} /><span>Melhor aproveitamento dos materiais recicláveis.</span></div><div><Check size={18} /><span>Mais segurança e organização para os trabalhadores.</span></div><div><Check size={18} /><span>Referência para estudos e projetos municipais.</span></div></div></article><aside className="feature-image"><img src={`${ASSET}2021/07/cidades.jpg`} alt="Paisagem de Mato Grosso do Sul" /><div><span className="doc-type">Material de referência</span><strong>Modelo de usina de triagem</strong><p>O projeto detalhado será conectado aos arquivos originais na etapa de documentos.</p></div></aside></div></section><section className="institutional-callout"><div className="container callout-inner"><div><Eyebrow>Próximo passo</Eyebrow><h2>Planejamento precisa conversar com a realidade local.</h2><p>Consulte os planos e panoramas municipais para entender as condições de cada cidade.</p></div><Link to="/cidades/" className="button button-dark">Consultar cidades <ArrowRight size={16} /></Link></div></section></>
}

export function SeparateWaste({ navigate }: { navigate: Navigate }) {
  const categories = [{ icon: <Recycle />, title: 'Recicláveis secos', text: 'Papel, papelão, plástico, metal e vidro limpos e secos. Separe, reduza o volume e encaminhe para a coleta seletiva.' }, { icon: <Leaf />, title: 'Orgânicos', text: 'Restos de alimentos e podas podem seguir para compostagem ou para a destinação indicada pelo serviço municipal.' }, { icon: <TriangleAlert />, title: 'Rejeitos e especiais', text: 'Materiais sem possibilidade de recuperação e resíduos que exigem cuidado devem seguir a orientação local.' }]
  return <><InstitutionalHero eyebrow="Educação ambiental" title="Como Separar Corretamente Seu Lixo" description="Pequenas decisões no dia a dia ajudam a reduzir impactos e fortalecem a reciclagem." crumbs={[{ label: 'Início', href: '/' }, { label: 'Como Separar Corretamente Seu Lixo' }]} /><section className="institutional-section section container"><div className="article-heading"><Eyebrow>Um hábito com impacto coletivo</Eyebrow><h2>Separar é o primeiro passo para dar o destino certo.</h2><p>Quando os materiais são separados corretamente, diminui a contaminação dos recicláveis, melhora o trabalho das cooperativas e aumenta o tempo de vida útil das estruturas de destinação.</p></div><div className="resource-grid education-grid">{categories.map((category) => <ResourceCard key={category.title} icon={category.icon} title={category.title} text={category.text} />)}</div><div className="steps-grid"><div><span>01</span><strong>Reduza</strong><p>Evite desperdícios e reaproveite materiais sempre que possível.</p></div><div><span>02</span><strong>Separe</strong><p>Coloque recicláveis limpos e secos separados dos orgânicos e rejeitos.</p></div><div><span>03</span><strong>Encaminhe</strong><p>Use a coleta seletiva ou os pontos de entrega indicados pelo município.</p></div></div></section><section className="institutional-callout"><div className="container callout-inner"><div><Eyebrow>Saiba mais</Eyebrow><h2>O destino final também importa.</h2><p>Entenda a diferença entre lixão, aterro sanitário e destinação ambientalmente adequada.</p></div><Link to="/diferenca-de-lixao-e-aterro-sanitario/" className="button button-dark">Entender a diferença <ArrowRight size={16} /></Link></div></section></>
}

export function LandfillDifference({ navigate }: { navigate: Navigate }) {
  return <><InstitutionalHero eyebrow="Educação ambiental" title="Diferença de Lixão e Aterro Sanitário" description="Destinação adequada exige controle, planejamento e proteção do solo, da água e das pessoas." crumbs={[{ label: 'Início', href: '/' }, { label: 'Diferença de Lixão e Aterro Sanitário' }]} /><section className="institutional-section section container"><div className="comparison-grid"><article className="comparison-card danger"><div className="comparison-icon"><TriangleAlert /></div><Eyebrow>Disposição inadequada</Eyebrow><h2>Lixão</h2><p>É o descarte de resíduos a céu aberto, sem controle ambiental, sem impermeabilização e sem tratamento adequado de líquidos e gases.</p><ul><li>Contaminação do solo e da água.</li><li>Proliferação de vetores e riscos à saúde.</li><li>Exposição de trabalhadores e comunidades.</li><li>Ausência de controle sobre os rejeitos.</li></ul></article><article className="comparison-card safe"><div className="comparison-icon"><ShieldCheck /></div><Eyebrow>Destinação adequada</Eyebrow><h2>Aterro sanitário</h2><p>É uma instalação planejada e licenciada para receber rejeitos, com técnicas de engenharia, operação controlada e monitoramento ambiental.</p><ul><li>Base impermeabilizada e drenagem controlada.</li><li>Tratamento de líquidos e gases.</li><li>Monitoramento e operação técnica.</li><li>Proteção ambiental e responsabilidade sanitária.</li></ul></article></div><div className="prose wide-prose"><h2>Resíduo não é tudo igual</h2><p>A coleta seletiva e a recuperação de materiais devem vir antes da disposição dos rejeitos. O aterro sanitário é destinado ao que não pode ser reaproveitado, reciclado ou tratado por outras soluções.</p><p>Por isso, a melhor política combina prevenção, redução, reutilização, reciclagem, tratamento e disposição final ambientalmente adequada.</p><Link to="/como-separar-corretamente-seu-lixo/" className="text-link">Voltar para as orientações de separação <ArrowRight size={15} /></Link></div></section></>
}

export function InstitutionalIcon({ type }: { type: 'water' | 'leaf' }) {
  return type === 'water' ? <Waves size={20} /> : <Leaf size={20} />
}
